/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intefaz;

import Aplicacion.Supertlon;
import Negocio.Socio;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author melidumanski
 */
public class VentanaCliente extends javax.swing.JFrame {
    
    private Supertlon controller;
    private Socio socioSeleccionado;
    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente(Supertlon controller) {
        initComponents();
        this.controller = controller;
        
        List<Socio> socios = Supertlon.mostrarSocios();
        DefaultComboBoxModel<String> opciones1 = new DefaultComboBoxModel<>();
        // Llenar el modelo con representaciones de los objetos Articulo
        if (socios.isEmpty()) {
            jComboBox1.addItem("NO EXISTEN SOCIOS");
        } else {
            for (Socio socio : socios) {
                opciones1.addElement(socio.getId() + " - " + socio.getNombre() + " " + socio.getApellido());
            }
            jComboBox1.setModel(opciones1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Lantinghei TC", 0, 18)); // NOI18N
        titulo.setText("CLIENTE");

        ingresar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titulo)
                .addGap(36, 36, 36)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        if (jComboBox1.getSelectedItem().equals("NO EXISTEN SOCIOS")) {
            JOptionPane.showMessageDialog(null, "No existen socios. Intente nuevamente más tarde.");
        } else {
            String seleccionado = jComboBox1.getSelectedItem().toString();
            String[] partes = seleccionado.split("\\ - ");
            int idSocio = Integer.parseInt(partes[0]);
            socioSeleccionado = Supertlon.buscarSocio(idSocio);
            VentanaCliente_AgregarClase ventanaCliente_AgregarClase = new VentanaCliente_AgregarClase(controller, socioSeleccionado);
            ventanaCliente_AgregarClase.setLocationRelativeTo(null);
            ventanaCliente_AgregarClase.setVisible(true);
        }
    }//GEN-LAST:event_ingresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
