/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intefaz;

import Aplicacion.Supertlon;

/**
 *
 * @author melidumanski
 */
public class VentanaSoporteTecnico extends javax.swing.JFrame {

    private Supertlon controller;
    
    /**
     * Creates new form VentanaServicioTecnico
     */
    public VentanaSoporteTecnico(Supertlon controller) {
        initComponents();
        // el controler debe ser el mismo del de la ventana principal. sino tendremos diferentes juegos de datos.
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        nuevaSede = new javax.swing.JButton();
        cargarUsuario = new javax.swing.JButton();
        cargarActividad = new javax.swing.JButton();
        cargarArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Lantinghei TC", 1, 18)); // NOI18N
        titulo.setText("SOPORTE TECNICO");

        nuevaSede.setText("Nueva Sede");
        nuevaSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaSedeActionPerformed(evt);
            }
        });

        cargarUsuario.setText("Cargar Usuario");
        cargarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarUsuarioActionPerformed(evt);
            }
        });

        cargarActividad.setText("Cargar Actividad");
        cargarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActividadActionPerformed(evt);
            }
        });

        cargarArticulo.setText("Cargar Articulo");
        cargarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArticuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cargarArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cargarActividad, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(cargarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nuevaSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(nuevaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cargarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cargarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cargarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaSedeActionPerformed
        // TODO add your handling code here:
        VentanaSoporteTecnico_NuevaSede ventanaSoporteTecnico_NuevaSede = new VentanaSoporteTecnico_NuevaSede(controller);
        ventanaSoporteTecnico_NuevaSede.setLocationRelativeTo(null);
        ventanaSoporteTecnico_NuevaSede.setVisible(true);
    }//GEN-LAST:event_nuevaSedeActionPerformed

    private void cargarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarUsuarioActionPerformed
        // TODO add your handling code here:
        VentanaSoporteTecnico_CargarUsuario ventanaSoporteTecnico_CargarUsuario = new VentanaSoporteTecnico_CargarUsuario(controller);
        ventanaSoporteTecnico_CargarUsuario.setLocationRelativeTo(null);
        ventanaSoporteTecnico_CargarUsuario.setVisible(true);
    }//GEN-LAST:event_cargarUsuarioActionPerformed

    private void cargarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActividadActionPerformed
        // TODO add your handling code here:
        VentanaSoporteTecnico_CargarActividad ventanaSoporteTecnico_CargarActividad = new VentanaSoporteTecnico_CargarActividad(controller);
        ventanaSoporteTecnico_CargarActividad.setLocationRelativeTo(null);
        ventanaSoporteTecnico_CargarActividad.setVisible(true);
    }//GEN-LAST:event_cargarActividadActionPerformed

    private void cargarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArticuloActionPerformed
        // TODO add your handling code here:
        VentanaSoporteTecnico_CargarArticulo ventanaSoporteTecnico_CargarArticulo = new VentanaSoporteTecnico_CargarArticulo(controller);
        ventanaSoporteTecnico_CargarArticulo.setLocationRelativeTo(null);
        ventanaSoporteTecnico_CargarArticulo.setVisible(true);
    }//GEN-LAST:event_cargarArticuloActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarActividad;
    private javax.swing.JButton cargarArticulo;
    private javax.swing.JButton cargarUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nuevaSede;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
