/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intefaz;

import Aplicacion.Supertlon;
import Negocio.TipoVidaUtil;

/**
 *
 * @author melidumanski
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPrincipal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        subtitulo = new javax.swing.JLabel();
        soporteTecnico = new javax.swing.JButton();
        administrativo = new javax.swing.JButton();
        cliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Lantinghei TC", 1, 24)); // NOI18N
        titulo.setText("SUPERTLON");

        subtitulo.setFont(new java.awt.Font("Nanum Myeongjo", 0, 14)); // NOI18N
        subtitulo.setText("Seleccionar el tipo de perfil de usuario el cual ingresará");

        soporteTecnico.setText("Soporte Técnico");
        soporteTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soporteTecnicoActionPerformed(evt);
            }
        });

        administrativo.setText("Administrativo");
        administrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrativoActionPerformed(evt);
            }
        });

        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaPrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(subtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaPrincipalLayout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaPrincipalLayout.createSequentialGroup()
                        .addGroup(VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(soporteTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(administrativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(125, 125, 125))))
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaPrincipalLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(subtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(soporteTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(administrativo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soporteTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soporteTecnicoActionPerformed
        // TODO add your handling code here:
        VentanaSoporteTecnico ventanaSoporteTecnico = new VentanaSoporteTecnico(controller);
        ventanaSoporteTecnico.setLocationRelativeTo(null);
        ventanaSoporteTecnico.setVisible(true);
    }//GEN-LAST:event_soporteTecnicoActionPerformed

    private void administrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrativoActionPerformed
        // TODO add your handling code here:
        VentanaAdministrativo_Seleccion ventanaAdministrativo_Seleccion = new VentanaAdministrativo_Seleccion(controller);
        ventanaAdministrativo_Seleccion.setLocationRelativeTo(null);
        ventanaAdministrativo_Seleccion.setVisible(true);
    }//GEN-LAST:event_administrativoActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
        VentanaCliente ventanaCliente = new VentanaCliente(controller);
        ventanaCliente.setLocationRelativeTo(null);
        ventanaCliente.setVisible(true);
    }//GEN-LAST:event_clienteActionPerformed

    private static Supertlon controller = new Supertlon();
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        Supertlon.crearActividad("Crossfit");
        Supertlon.crearActividad("Yoga");
        Supertlon.crearActividad("Kangoo jumping");
        Supertlon.crearActividad("Gimnasia postural");
        Supertlon.crearActividad("Aero combat");
        
        controller.crearActividadOnLine("Crossfit");
        controller.crearActividadOnLine("Yoga");
        controller.crearClaseOnLine("Crossfit", 10);
        controller.crearClaseOnLine("Yoga", 10);
        

        controller.crearLocalidad("Avellaneda");
        controller.crearLocalidad("Palermo");
        controller.crearLocalidad("Recoleta");
        controller.crearLocalidad("Puerto Madero");
        
        controller.crearArticulo("Pesa Rusa", 2023, 10, 20, TipoVidaUtil.USO, 200, "Sport");
        controller.crearArticulo("Polea", 2022, 1, 22, TipoVidaUtil.FECHA_FABRICACION, 650, "Machine 2.0");
        controller.crearArticulo("Soga", 2023, 4, 6, TipoVidaUtil.USO, 300, "Machine 2.0");
        controller.crearArticulo("Colchoneta", 2023, 12, 2, TipoVidaUtil.FECHA_FABRICACION, 600, "Machine 2.0");
        
        controller.crearProfesor("Tomas", "Lopez");
        controller.crearProfesor("Laura", "Martino");
        controller.crearProfesor("Gonzalo", "Perez");
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
   
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VentanaPrincipal;
    private javax.swing.JButton administrativo;
    private javax.swing.JButton cliente;
    private javax.swing.JButton soporteTecnico;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
