/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intefaz;

import Aplicacion.Supertlon;
import Negocio.*;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author melidumanski
 */
public class VentanaAdministrativo_Articulos extends javax.swing.JFrame {
    private Supertlon controller;
    private Sede sedeSeleccionada;
    /**
     * Creates new form VentanaAdministrativo_Articulos
     */
    public VentanaAdministrativo_Articulos(Supertlon controller, Sede sedeSeleccionada) {
        initComponents();
        this.controller = controller;
        this.sedeSeleccionada = sedeSeleccionada;
        
        List<Articulo> Articulos = Supertlon.mostrarArticulosDeSede(sedeSeleccionada);
        DefaultListModel<String> opciones1 = new DefaultListModel<>();
        DefaultComboBoxModel<String> opciones2 = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> opciones3 = new DefaultComboBoxModel<>();
        // Llenar el modelo con representaciones de los objetos Articulo
        if (Articulos.isEmpty()) {
            opciones1.addElement("NO EXISTEN ARTICULOS");
            jComboBox1.addItem("NO EXISTEN ARTICULOS");
            jComboBox2.addItem("NO EXISTEN ARTICULOS");
        } else {
            for (Articulo articulo : Articulos) {
                opciones1.addElement(articulo.getId() + " - " + "Nombre: " + articulo.getNombre() + " - Marca: " + articulo.getMarca());
                opciones2.addElement(articulo.getId() + " - " + "Nombre: " + articulo.getNombre() + " - Marca: " + articulo.getMarca());
                opciones3.addElement(articulo.getId() + " - " + "Nombre: " + articulo.getNombre() + " - Marca: " + articulo.getMarca());
            }
            jComboBox1.setModel(opciones2);
            jComboBox2.setModel(opciones3);
        }
        jList1.setModel(opciones1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lantinghei TC", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OPCIONES ARTICULOS");

        jScrollPane1.setViewportView(jList1);

        jLabel2.setFont(new java.awt.Font("Nanum Myeongjo", 0, 14)); // NOI18N
        jLabel2.setText("Articulos disponibles de la Sede :");

        jLabel3.setFont(new java.awt.Font("Nanum Myeongjo", 0, 14)); // NOI18N
        jLabel3.setText("Ver cúal es el estado de su desgaste :");

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton1.setText("Ver desgaste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nanum Myeongjo", 0, 14)); // NOI18N
        jLabel4.setText("Dar de baja artículo :");

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2.setText("Dar de Baja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().equals("NO EXISTEN ARTICULOS")) {
            JOptionPane.showMessageDialog(null, "No existen articulos, intente más tarde.");       
        } else { 
            String seleccionado = jComboBox1.getSelectedItem().toString(); // agarro la opcion seleccionada
            String[] partes = seleccionado.split("\\ - "); // separo string de JComboBox para tener ID
            int id = Integer.parseInt(partes[0]); // guardo el ID para buscarlo en la lista de Sedes
            Articulo articulo = Supertlon.buscarArticuloEnSede(id, sedeSeleccionada);
            TipoVidaUtil tipo = Supertlon.buscarTipoVidaUtilDeArticulo(articulo);
            String vidaUtil;
            if (articulo.getTipoVidaUtil().equals(TipoVidaUtil.FECHA_FABRICACION)) {
                vidaUtil = "Dias";
            } else {
                vidaUtil = "Usos";
            }
            int desgaste = Supertlon.calcularDesgaste(articulo);
            JOptionPane.showMessageDialog(null, "Se calcula el desgaste del artículo con ID: "+ id + " - Tiene disponible: "+ desgaste + " " + vidaUtil);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int num = jComboBox2.getSelectedIndex();
        if (jComboBox2.getSelectedItem().equals("NO EXISTEN ARTICULOS")) {
            JOptionPane.showMessageDialog(null, "No existen articulos, intente más tarde.");       
        } else { 
            String seleccionado = jComboBox2.getSelectedItem().toString(); // agarro la opcion seleccionada
            String[] partes = seleccionado.split("\\ - "); // separo string de JComboBox para tener ID
            int id = Integer.parseInt(partes[0]); // guardo el ID para buscarlo en la lista de Sedes
            Articulo articulo = Supertlon.buscarArticuloEnSede(id, sedeSeleccionada);
            Supertlon.eliminarArticuloEnSede(articulo, sedeSeleccionada);
            jComboBox2.removeItemAt(num);
            jComboBox1.removeItemAt(num);
        }
        if (jComboBox2.getItemCount() == 0) {
            jComboBox2.addItem("NO EXISTEN ARTICULOS");
            jComboBox1.addItem("NO EXISTEN ARTICULOS");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
